name = "babyplan-backend"
main = "src/index.js"
compatibility_date = "2026-06-18"

# Environmental variables
[vars]
FIREBASE_PROJECT_ID = "babyplan-auth"

# KV Namespace bindings
[[kv_namespaces]]
binding = "BABYPLAN_KV"
id = "507bfaf0b4da498b94759e7b2e253fc7"

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "babyplan-db"
database_id = "c3d1494e-8bca-4a6d-a31d-5db283013beb"
