import { 
  PregnancyProfile, 
  BudgetItem, 
  WishlistItem, 
  ChecklistItem, 
  MedicalVisit, 
  BabyName, 
  HospitalBagItem, 
  HospitalComparison 
} from "./types";

// Scenario: Moms Clarissa & Dads Ardi, expecting baby "Aisha"
// HPHT: Jan 15, 2026 (approx 21 weeks pregnancy, Trimester 2, Fruit: Carrot / Pomegranate)
// HPL: Oct 22, 2026 (approx 132 days remaining)

export const mockProfile: PregnancyProfile = {
  userId: "preview_user_id",
  namaMoms: "Moms Clarissa",
  namaDads: "Dads Ardi",
  namaBayi: "Dek Aisha",
  hpht: "2026-01-15",
  hpl: "2026-10-22",
  pilihanPerhitungan: "HPHT",
  targetBudget: 45000000, // Rp 45.000.000
  mataUang: "Rp (Rupiah)",
  createdAt: "2026-02-01T08:00:00Z",
  updatedAt: "2026-02-01T08:00:00Z"
};

export const mockBudgetItems: BudgetItem[] = [
  // MEIDK & KONTROL (Kategori: Medis & Kontrol)
  {
    id: "b1",
    userId: "preview_user_id",
    tanggal: "2026-02-12",
    nama: "Pemeriksaan USG Pertama & Vitamin",
    kategori: "Medis & Kontrol",
    subkategori: "Kontrol Bulanan Dokter",
    prioritas: "Tinggi",
    rencana: 850000,
    aktual: 890000,
    statusPembayaran: "Lunas",
    metode: "Kartu Debit",
    catatan: "Klinik Sehati. Dokter Amanda, SpOG. Vitamin asam folat untuk 1 bulan.",
    createdAt: "2026-02-12T10:00:00Z",
    updatedAt: "2026-02-12T10:00:00Z"
  },
  {
    id: "b2",
    userId: "preview_user_id",
    tanggal: "2026-03-15",
    nama: "Kontrol Rutin & Vitamin Trimester 1",
    kategori: "Medis & Kontrol",
    subkategori: "Kontrol Bulanan Dokter",
    prioritas: "Tinggi",
    rencana: 750000,
    aktual: 720000,
    statusPembayaran: "Lunas",
    metode: "Transfer Bank",
    catatan: "Kontrol trimester pertama lancar, janin berkembang baik.",
    createdAt: "2026-03-15T11:00:00Z",
    updatedAt: "2026-03-15T11:00:00Z"
  },
  {
    id: "b3",
    userId: "preview_user_id",
    tanggal: "2026-04-18",
    nama: "Cek Darah Lengkap & Urine Lab",
    kategori: "Medis & Kontrol",
    subkategori: "Laboratorium",
    prioritas: "Tinggi",
    rencana: 1200000,
    aktual: 1150000,
    statusPembayaran: "Lunas",
    metode: "Kartu Kredit",
    catatan: "Untuk skrining diabetes gestasional dan kadar zat besi. Hasil normal.",
    createdAt: "2026-04-18T09:00:00Z",
    updatedAt: "2026-04-18T09:00:00Z"
  },
  {
    id: "b4",
    userId: "preview_user_id",
    tanggal: "2026-05-15",
    nama: "Kontrol Dokter Trimester 2 & Kalsium",
    kategori: "Medis & Kontrol",
    subkategori: "Kontrol Bulanan Dokter",
    prioritas: "Tinggi",
    rencana: 750000,
    aktual: 780000,
    statusPembayaran: "Lunas",
    metode: "Cash",
    catatan: "Dokter memberi resep tambahan kalsium dan DHA.",
    createdAt: "2026-05-15T10:00:00Z",
    updatedAt: "2026-05-15T10:00:00Z"
  },
  {
    id: "b4-nipt",
    userId: "preview_user_id",
    tanggal: "2026-04-20",
    nama: "Tes Genetik Janin NIPT Premium",
    kategori: "Medis & Kontrol",
    subkategori: "Laboratorium",
    prioritas: "Sedang",
    rencana: 7500000,
    aktual: 7300000,
    statusPembayaran: "Lunas",
    metode: "Kartu Kredit",
    catatan: "Deteksi kromosom dan kesehatan DNA. Hasil puji tuhan normal & berjenis kelamin perempuan.",
    createdAt: "2026-04-20T09:00:00Z",
    updatedAt: "2026-04-20T09:00:00Z"
  },
  {
    id: "b_yoga",
    userId: "preview_user_id",
    tanggal: "2026-05-25",
    nama: "Sesi Prenatal Yoga di Studio Bumi",
    kategori: "Medis & Kontrol",
    subkategori: "Olahraga/Kelas Hamil",
    prioritas: "Sedang",
    rencana: 450000,
    aktual: 450000,
    statusPembayaran: "Lunas",
    metode: "Qris",
    catatan: "Paket 4 sesi latihan pernapasan dan peregangan panggul.",
    createdAt: "2026-05-25T14:00:00Z",
    updatedAt: "2026-05-25T14:00:00Z"
  },
  {
    id: "b_kontrol3",
    userId: "preview_user_id",
    tanggal: "2026-08-20",
    nama: "Rencana Kontrol Rutin Trimester 3",
    kategori: "Medis & Kontrol",
    subkategori: "Kontrol Bulanan Dokter",
    prioritas: "Tinggi",
    rencana: 900000,
    aktual: 0,
    statusPembayaran: "Belum Lunas",
    metode: "Belum Ditentukan",
    catatan: "USG akhir trimester 3 untuk melihat posisi kepala bayi dan plasenta.",
    createdAt: "2026-06-01T08:00:00Z",
    updatedAt: "2026-06-01T08:00:00Z"
  },

  // PERLENGKAPAN BAYI (Kategori: Perlengkapan Bayi)
  {
    id: "b5",
    userId: "preview_user_id",
    tanggal: "2026-06-05",
    nama: "Box Bayi Kayu Minimalis (Baby Crib)",
    kategori: "Perlengkapan Bayi",
    subkategori: "Furnitur Kamar",
    prioritas: "Sedang",
    rencana: 2500000,
    aktual: 2300000,
    statusPembayaran: "Lunas",
    metode: "Transfer Bank",
    catatan: "Beli merek lokal kayu solid mahoni, sudah termasuk kasur busa bebas alergi.",
    createdAt: "2026-06-05T14:00:00Z",
    updatedAt: "2026-06-05T14:00:00Z"
  },
  {
    id: "b_stroller",
    userId: "preview_user_id",
    tanggal: "2026-06-10",
    nama: "Stroller Cabin-size Ringan",
    kategori: "Perlengkapan Bayi",
    subkategori: "Mobilitas Bayi",
    prioritas: "Tinggi",
    rencana: 3500000,
    aktual: 3250000,
    statusPembayaran: "Lunas",
    metode: "Debit",
    catatan: "Mudah dilipat satu tangan, kokoh, dan aman.",
    createdAt: "2026-06-10T11:00:00Z",
    updatedAt: "2026-06-10T11:00:00Z"
  },
  {
    id: "b6",
    userId: "preview_user_id",
    tanggal: "2026-08-10",
    nama: "Paket Baju Bayi New Born (Katun Organik)",
    kategori: "Perlengkapan Bayi",
    subkategori: "Pakaian & Sandang",
    prioritas: "Tinggi",
    rencana: 1500000,
    aktual: 0,
    statusPembayaran: "Belum Lunas",
    metode: "Belum Ditentukan",
    catatan: "Beli isi 12 pasang baju dan celana katun adem pasca usia kehamilan 30 minggu.",
    createdAt: "2026-05-10T12:00:00Z",
    updatedAt: "2026-05-10T12:00:00Z"
  },
  {
    id: "b_skincare",
    userId: "preview_user_id",
    tanggal: "2026-06-02",
    nama: "Paket Skincare & Sabun Bayi Sensitive",
    kategori: "Perlengkapan Bayi",
    subkategori: "Perawatan Kulit",
    prioritas: "Sedang",
    rencana: 500000,
    aktual: 485000,
    statusPembayaran: "Lunas",
    metode: "Qris",
    catatan: "Paket Mustela newborn: diaper cream, hair lotion, gentle bath gel.",
    createdAt: "2026-06-02T10:00:00Z",
    updatedAt: "2026-06-02T10:00:00Z"
  },

  // KEBUTUHAN IBU (Kategori: Kebutuhan Ibu)
  {
    id: "b_pillow",
    userId: "preview_user_id",
    tanggal: "2026-03-20",
    nama: "Maternity Pillow (Bantal Ibu Hamil)",
    kategori: "Kebutuhan Ibu",
    subkategori: "Kamar & Istirahat",
    prioritas: "Sedang",
    rencana: 250000,
    aktual: 235000,
    statusPembayaran: "Lunas",
    metode: "Cash",
    catatan: "Bentuk C-shape sangat menolong posisi tidur miring kiri Moms.",
    createdAt: "2026-03-20T11:00:00Z",
    updatedAt: "2026-03-20T11:00:00Z"
  },
  {
    id: "b_daster",
    userId: "preview_user_id",
    tanggal: "2026-05-30",
    nama: "Setel Daster & Kaos Menyusui (Busui)",
    kategori: "Kebutuhan Ibu",
    subkategori: "Pakaian Ibu",
    prioritas: "Tinggi",
    rencana: 450000,
    aktual: 450000,
    statusPembayaran: "Lunas",
    metode: "Qris",
    catatan: "Beli 4 buah pakaian berkancing di depan untuk kemudahan pumping nanti.",
    createdAt: "2026-05-30T10:00:00Z",
    updatedAt: "2026-05-30T10:00:00Z"
  },
  {
    id: "b_pompa",
    userId: "preview_user_id",
    tanggal: "2026-07-15",
    nama: "Handsfree Breastpump Double Elektrik",
    kategori: "Kebutuhan Ibu",
    subkategori: "Peralatan Menyusui",
    prioritas: "Tinggi",
    rencana: 850000,
    aktual: 0,
    statusPembayaran: "Belum Lunas",
    metode: "Belum Ditentukan",
    catatan: "Gabag Kolibri Max untuk persiapan pumping ASI saat Moms kembali bekerja.",
    createdAt: "2026-06-01T08:00:00Z",
    updatedAt: "2026-06-01T08:00:00Z"
  },

  // BIAYA PERSALINAN (Kategori: Biaya Melahirkan & RS)
  {
    id: "b_caesar",
    userId: "preview_user_id",
    tanggal: "2026-10-22",
    nama: "Dana Utama Persalinan Caesar ERACS VIP RSIA",
    kategori: "Biaya Melahirkan & RS",
    subkategori: "Tindakan Persalinan",
    prioritas: "Tinggi",
    rencana: 25000000,
    aktual: 0,
    statusPembayaran: "Belum Lunas",
    metode: "Belum Ditentukan",
    catatan: "Estimasi biaya di RSIA Bunda Menteng. Sedang ditabung berkala gratis asuransi.",
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z"
  },
  {
    id: "b_booking_rs",
    userId: "preview_user_id",
    tanggal: "2026-06-01",
    nama: "Deposit Booking Kamar Bersalin & Administrasi",
    kategori: "Biaya Melahirkan & RS",
    subkategori: "Tindakan Persalinan",
    prioritas: "Tinggi",
    rencana: 2000000,
    aktual: 2000000,
    statusPembayaran: "Lunas",
    metode: "Transfer Bank",
    catatan: "Sudah dipesan agar reservasi kelas VIP aman dan masuk dalam slot promonya.",
    createdAt: "2026-06-01T10:00:00Z",
    updatedAt: "2026-06-01T10:00:00Z"
  },

  // ACARA & LAIN-LAIN (Kategori: Acara & Syukuran)
  {
    id: "b_mitoni",
    userId: "preview_user_id",
    tanggal: "2026-08-15",
    nama: "Upacara Adat Mitoni (7 Bulanan Kehamilan)",
    kategori: "Acara & Syukuran",
    subkategori: "Upacara Adat/Syukuran",
    prioritas: "Sedang",
    rencana: 5000000,
    aktual: 0,
    statusPembayaran: "Belum Lunas",
    metode: "Belum Ditentukan",
    catatan: "Acara doa syukuran keluarga inti, tumpeng pusaka, dan hampers besek kerabat terdekat.",
    createdAt: "2026-06-01T10:00:00Z",
    updatedAt: "2026-06-01T10:00:00Z"
  },
  {
    id: "b_maternity_photo",
    userId: "preview_user_id",
    tanggal: "2026-06-11",
    nama: "Sesi Foto Kehamilan (Maternity Photoshoot)",
    kategori: "Acara & Syukuran",
    subkategori: "Dokumentasi",
    prioritas: "Rendah",
    rencana: 1500000,
    aktual: 1500000,
    statusPembayaran: "Lunas",
    metode: "Transfer Bank",
    catatan: "Sesi foto manis bersama Dads Ardi di studio minimalis.",
    createdAt: "2026-06-11T12:00:00Z",
    updatedAt: "2026-06-11T12:00:00Z"
  }
];

export const mockWishlistItems: WishlistItem[] = [
  {
    id: "w1",
    userId: "preview_user_id",
    nama: "Sterilizer Botol Susu UV Guard",
    kategori: "Peralatan Makan & Susu",
    brand: "BabySafe UV Sterilizer V2",
    estimasi: 1200000,
    hargaAktual: 1150000,
    jumlah: 1,
    link: "https://shopee.co.id",
    status: "Sudah Dibeli",
    prioritas: "Sedang",
    catatan: "Banyak direkomendasikan karena praktis daripada merebus air manual secara konvensional.",
    createdAt: "2026-05-02T10:00:00Z",
    updatedAt: "2026-06-12T10:00:00Z"
  },
  {
    id: "w2",
    userId: "preview_user_id",
    nama: "Kasur Bayi Hipoalergenik Organik",
    kategori: "Furnitur Kamar",
    brand: "Dooglee Latex Premium",
    estimasi: 1850000,
    hargaAktual: 0,
    jumlah: 1,
    link: "https://shopee.co.id",
    status: "Belum Dibeli",
    prioritas: "Tinggi",
    catatan: "Sangat direkomendasikan untuk mencegah alergi kulit pada newborn baby.",
    createdAt: "2026-05-12T11:00:00Z",
    updatedAt: "2026-05-12T11:00:00Z"
  },
  {
    id: "w3",
    userId: "preview_user_id",
    nama: "Air Purifier Kamar Bayi (HEPA Filter)",
    kategori: "Furnitur Kamar",
    brand: "Xiaomi Smart Air Purifier 4 Compact",
    estimasi: 1400000,
    hargaAktual: 0,
    jumlah: 1,
    link: "https://tokopedia.com",
    status: "Belum Dibeli",
    prioritas: "Sedang",
    catatan: "Sangat penting agar sirkulasi udara kamar bayi bebas debu, virus, dan bau.",
    createdAt: "2026-05-20T09:00:00Z",
    updatedAt: "2026-05-20T09:00:00Z"
  },
  {
    id: "w4",
    userId: "preview_user_id",
    nama: "Bouncer Bayi Elektrik (Automatic Swing)",
    kategori: "Peralatan Makan & Susu",
    brand: "Sugar Baby Hug Me Electric Swing",
    estimasi: 650000,
    hargaAktual: 0,
    jumlah: 1,
    link: "https://tokopedia.com",
    status: "Belum Dibeli",
    prioritas: "Rendah",
    catatan: "Diletakkan di wishlist, siapa tahu ada rekan kantor yang ingin memberi kado lahiran.",
    createdAt: "2026-05-25T11:00:00Z",
    updatedAt: "2026-05-25T11:00:00Z"
  },
  {
    id: "w5",
    userId: "preview_user_id",
    nama: "Termometer Inframerah Medis",
    kategori: "Perlengkapan Ibu",
    brand: "Braun Thermoscan 7",
    estimasi: 1100000,
    hargaAktual: 1100000,
    jumlah: 1,
    link: "https://shopee.co.id",
    status: "Sudah Dibeli",
    prioritas: "Tinggi",
    catatan: "Wajib punya sebelum bayi lahir untuk indikator demam akurat via telinga.",
    createdAt: "2026-05-10T11:00:00Z",
    updatedAt: "2026-06-01T11:00:00Z"
  }
];

export const mockChecklistItems: ChecklistItem[] = [
  // Trimester 1
  {
    id: "c1",
    userId: "preview_user_id",
    judul: "Tes pack berkala & tes serum darah untuk konfirmasi kehamilan",
    trimester: 1,
    bulan: "Bulan 1",
    kategori: "Kesehatan",
    status: "Selesai",
    createdAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-04-01T10:00:00Z"
  },
  {
    id: "c1-folat",
    userId: "preview_user_id",
    judul: "Minum Vitamin Asam Folat 400mcg rutin setiap hari",
    trimester: 1,
    bulan: "Bulan 1",
    kategori: "Kesehatan",
    status: "Selesai",
    createdAt: "2026-01-21T10:00:00Z",
    updatedAt: "2026-01-21T10:00:00Z"
  },
  {
    id: "c2",
    userId: "preview_user_id",
    judul: "Skrining Awal & USG Pertama dengan Obgyn",
    trimester: 1,
    bulan: "Bulan 2",
    kategori: "Kunjungan Rumah Sakit",
    status: "Selesai",
    createdAt: "2026-02-12T10:00:00Z",
    updatedAt: "2026-02-12T10:00:00Z"
  },
  {
    id: "c_morningsick",
    userId: "preview_user_id",
    judul: "Atasi morning sickness dengan teh jahe hangat & cemilan kering",
    trimester: 1,
    bulan: "Bulan 2",
    kategori: "Kesehatan",
    status: "Selesai",
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-02-15T10:00:00Z"
  },
  {
    id: "c_choose_dr",
    userId: "preview_user_id",
    judul: "Riset dan pilih dokter Obgyn / Bidan yang supportif pro-normal",
    trimester: 1,
    bulan: "Bulan 3",
    kategori: "Riset Rumah Sakit",
    status: "Selesai",
    createdAt: "2026-03-05T10:00:00Z",
    updatedAt: "2026-03-05T10:00:00Z"
  },

  // Trimester 2
  {
    id: "c3",
    userId: "preview_user_id",
    judul: "Mulai memilah & membandingkan paket persalinan Rumah Sakit Bersalin",
    trimester: 2,
    bulan: "Bulan 4",
    kategori: "Riset Rumah Sakit",
    status: "Selesai",
    createdAt: "2026-04-10T10:00:00Z",
    updatedAt: "2026-05-15T10:00:00Z"
  },
  {
    id: "c_nipt_test",
    userId: "preview_user_id",
    judul: "Lakukan tes genetika janin (NIPS/NIPT) & USG detail Fetomaternal",
    trimester: 2,
    bulan: "Bulan 4",
    kategori: "Kesehatan",
    status: "Selesai",
    createdAt: "2026-04-12T10:00:00Z",
    updatedAt: "2026-04-20T10:00:00Z"
  },
  {
    id: "c_stretch",
    userId: "preview_user_id",
    judul: "Beli dan pakai Stretch Mark Cream/Oil untuk area perut & paha",
    trimester: 2,
    bulan: "Bulan 5",
    kategori: "Kesehatan",
    status: "Selesai",
    createdAt: "2026-05-02T10:00:00Z",
    updatedAt: "2026-05-02T10:00:00Z"
  },
  {
    id: "c_saving_plan",
    userId: "preview_user_id",
    judul: "Buat alokasi tabungan berjangka khusus untuk dana melahirkan",
    trimester: 2,
    bulan: "Bulan 5",
    kategori: "Keuangan",
    status: "Selesai",
    createdAt: "2026-05-10T10:00:00Z",
    updatedAt: "2026-05-10T10:00:00Z"
  },
  {
    id: "c_senam",
    userId: "preview_user_id",
    judul: "Daftar kelas prenatal yoga atau pilates hamil untuk kebugaran fisik",
    trimester: 2,
    bulan: "Bulan 6",
    kategori: "Kesehatan",
    status: "Selesai",
    createdAt: "2026-05-20T10:00:00Z",
    updatedAt: "2026-05-25T10:00:00Z"
  },

  // Trimester 3
  {
    id: "c_bag_pack",
    userId: "preview_user_id",
    judul: "Rapikan dokumen & paking tas bersalin (Hospital Bag) Moms & Bayi",
    trimester: 3,
    bulan: "Bulan 8",
    kategori: "Persiapan Melahirkan",
    status: "Belum Selesai",
    createdAt: "2026-06-01T10:00:00Z",
    updatedAt: "2026-06-01T10:00:00Z"
  },
  {
    id: "c_laktasi_class",
    userId: "preview_user_id",
    judul: "Ikuti kelas edukasi laktasi online/offline bersama suami tercinta",
    trimester: 3,
    bulan: "Bulan 8",
    kategori: "Pendidikan & Kelas",
    status: "Belum Selesai",
    createdAt: "2026-06-02T10:00:00Z",
    updatedAt: "2026-06-02T10:00:00Z"
  },
  {
    id: "c_pijat_perineum",
    userId: "preview_user_id",
    judul: "Lakukan pijat perineum mandiri bertahap untuk kelenturan jalan lahir",
    trimester: 3,
    bulan: "Bulan 9",
    kategori: "Kesehatan",
    status: "Belum Selesai",
    createdAt: "2026-06-03T10:00:00Z",
    updatedAt: "2026-06-03T10:00:00Z"
  },
  {
    id: "c_tanda_lahiran",
    userId: "preview_user_id",
    judul: "Pahami tanda-tanda asli melahirkan (pecah ketuban, lendir darah)",
    trimester: 3,
    bulan: "Bulan 9",
    kategori: "Persiapan Melahirkan",
    status: "Belum Selesai",
    createdAt: "2026-06-04T10:00:00Z",
    updatedAt: "2026-06-04T10:00:00Z"
  }
];

export const mockMedicalVisits: MedicalVisit[] = [
  {
    id: "mv1",
    userId: "preview_user_id",
    tanggalKunjungan: "2026-02-15",
    usiaKehamilan: "4 Minggu 0 Hari",
    dokterBidan: "Dr. Amanda, SpOG",
    tempat: "Klinik Utama Sehati",
    tensi: "118/76",
    beratBadan: "54.2",
    hasilCatatan: "Kantung kehamilan nampak ukuran sferis 1.2 cm, posisi aman di fundus uteri.",
    biaya: 850000,
    resepVitamin: "Asam Folat 400 mcg",
    jadwalBerikutnya: "2026-03-15",
    createdAt: "2026-02-15T11:00:00Z",
    updatedAt: "2026-02-15T11:00:00Z"
  },
  {
    id: "mv2",
    userId: "preview_user_id",
    tanggalKunjungan: "2026-03-15",
    usiaKehamilan: "8 Minggu 1 Hari",
    dokterBidan: "Dr. Amanda, SpOG",
    tempat: "Klinik Utama Sehati",
    tensi: "120/80",
    beratBadan: "54.8",
    hasilCatatan: "Detak jantung bayi terdengar kuat berirama (142 bpm), CRL berukuran 2.1 cm.",
    biaya: 720000,
    resepVitamin: "Promavit multivitamin, suplemen kalsium",
    jadwalBerikutnya: "2026-04-15",
    createdAt: "2026-03-15T12:00:00Z",
    updatedAt: "2026-03-15T12:00:00Z"
  },
  {
    id: "mv3",
    userId: "preview_user_id",
    tanggalKunjungan: "2026-04-15",
    usiaKehamilan: "12 Minggu 4 Hari",
    dokterBidan: "Dr. Amanda, SpOG",
    tempat: "Klinik Utama Sehati",
    tensi: "115/78",
    beratBadan: "55.5",
    hasilCatatan: "USG detail mengonfirmasi tulang hidung terbentuk, tebal tengkuk Nuchal Translucency normal (NT: 1.3 mm).",
    biaya: 950000,
    resepVitamin: "Folamil Genio, Osteocare Kalsium, serat makanan tambahan",
    jadwalBerikutnya: "2026-05-15",
    createdAt: "2026-04-15T10:00:00Z",
    updatedAt: "2026-04-15T10:00:00Z"
  },
  {
    id: "mv4",
    userId: "preview_user_id",
    tanggalKunjungan: "2026-05-15",
    usiaKehamilan: "16 Minggu 6 Hari",
    dokterBidan: "Dr. Amanda, SpOG",
    tempat: "Klinik Utama Sehati",
    tensi: "117/74",
    beratBadan: "57.2",
    hasilCatatan: "Gerakan halus bayi mulai terasa lembut, detak jantung 148 bpm. Kondisi plasenta di atas aman.",
    biaya: 750000,
    resepVitamin: "Folamil Genio, Kalsium Sandoz, Sangobion Zat Besi",
    jadwalBerikutnya: "2026-06-15",
    createdAt: "2026-05-15T11:00:00Z",
    updatedAt: "2026-05-15T11:00:00Z"
  }
];

export const mockBabyNames: BabyName[] = [
  {
    id: "n1",
    userId: "preview_user_id",
    nama: "Aisha Az-Zahra",
    gender: "Perempuan",
    asal: "Arab",
    arti: "Gadis yang hidup bahagia, suci, cantik bersinar bagai bunga indah",
    panggilan: "Aisha / Zahra",
    catatan: "Nama yang sangat disukai Moms karena maknanya yang mulis dan terdengar sangat anggun.",
    statusPilihan: "Pilihan Utama",
    isFavorite: true,
    votes: 8,
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z"
  },
  {
    id: "n2",
    userId: "preview_user_id",
    nama: "Kirana Syifa",
    gender: "Perempuan",
    asal: "Jawa Sansekerta",
    arti: "Cahaya redup nan cantik mempesona, obat penyejuk jiwa yang tulus",
    panggilan: "Kirana",
    catatan: "Usulan dari nenek buyut, memiliki nuansa lokal Jawa halus nan kharismatik.",
    statusPilihan: "Favorit",
    isFavorite: true,
    votes: 14,
    createdAt: "2026-03-05T12:00:00Z",
    updatedAt: "2026-03-05T12:00:00Z"
  },
  {
    id: "n3",
    userId: "preview_user_id",
    nama: "Kayla Nadhira",
    gender: "Perempuan",
    asal: "Arab & Persia",
    arti: "Mahkota kemenangan yang terpilih, elok dipandang, kaya akan karunia",
    panggilan: "Kayla",
    catatan: "Artinya sangat kuat, mewakili harapan orang tua agar si kecil selalu beruntung.",
    statusPilihan: "Pertimbangan",
    isFavorite: false,
    votes: 11,
    createdAt: "2026-03-10T10:00:00Z",
    updatedAt: "2026-03-10T10:00:00Z"
  },
  {
    id: "n4",
    userId: "preview_user_id",
    nama: "Rania Farasya",
    gender: "Perempuan",
    asal: "Masyarakat Modern",
    arti: "Ratu anggun nan mempesona, pembawa kehangatan dan periang",
    panggilan: "Rania",
    catatan: "Modern dan dinamis. Sangat mudah diingat dan dieja dengan baik.",
    statusPilihan: "Pilihan Kami",
    isFavorite: true,
    votes: 5,
    createdAt: "2026-03-15T11:00:00Z",
    updatedAt: "2026-03-15T11:00:00Z"
  },
  {
    id: "n5",
    userId: "preview_user_id",
    nama: "Zayn Arsalan",
    gender: "Laki-laki",
    asal: "Arab Islami",
    arti: "Perhiasan keindahan akhlak, berani bagai singa, pemimpin tangguh penolong sesama",
    panggilan: "Zayn",
    catatan: "Rekomendasi dari Dads. Terdengar berwibawa dan maskulin.",
    statusPilihan: "Pilihan Utama",
    isFavorite: false,
    votes: 2,
    createdAt: "2026-03-20T10:00:00Z",
    updatedAt: "2026-03-20T10:00:00Z"
  }
];

export const mockHospitalBagItems: HospitalBagItem[] = [
  {
    id: "hb1",
    userId: "preview_user_id",
    barang: "Daster katun adem kancing depan (Busui-friendly)",
    kategori: "Perlengkapan Ibu",
    jumlah: 3,
    status: "Siap",
    createdAt: "2026-05-10T09:00:00Z",
    updatedAt: "2026-06-01T09:00:00Z"
  },
  {
    id: "hb_pembalut",
    userId: "preview_user_id",
    barang: "Pembalut bersalin (Maternity Pads) ukuran jumbo nifas",
    kategori: "Perlengkapan Ibu",
    jumlah: 2,
    status: "Siap",
    createdAt: "2026-05-11T09:00:00Z",
    updatedAt: "2026-06-01T09:00:00Z"
  },
  {
    id: "hb_bra",
    userId: "preview_user_id",
    barang: "Bra khusus menyusui & pad penyerap disposable",
    kategori: "Perlengkapan Ibu",
    jumlah: 3,
    status: "Belum Siap",
    createdAt: "2026-05-12T09:00:00Z",
    updatedAt: "2026-05-12T09:00:00Z"
  },
  {
    id: "hb2",
    userId: "preview_user_id",
    barang: "Kain bedong, gurita katun bayi, & kaos kaki tangan newborn",
    kategori: "Perlengkapan Bayi",
    jumlah: 6,
    status: "Siap",
    createdAt: "2026-05-11T09:00:00Z",
    updatedAt: "2026-06-02T09:00:00Z"
  },
  {
    id: "hb_diaper",
    userId: "preview_user_id",
    barang: "Popok bayi baru lahir sekali pakai (Newborn Diapers)",
    kategori: "Perlengkapan Bayi",
    jumlah: 15,
    status: "Siap",
    createdAt: "2026-05-15T10:00:00Z",
    updatedAt: "2026-05-15T10:00:00Z"
  },
  {
    id: "hb_babyout",
    userId: "preview_user_id",
    barang: "Setelan baju pulang bayi newborn & topi hangat",
    kategori: "Perlengkapan Bayi",
    jumlah: 2,
    status: "Siap",
    createdAt: "2026-05-16T10:00:00Z",
    updatedAt: "2026-05-16T10:00:00Z"
  },
  {
    id: "hb_dadsout",
    userId: "preview_user_id",
    barang: "Pakaian ganti & perlengkapan mandi personal Dads",
    kategori: "Perlengkapan Ayah",
    jumlah: 2,
    status: "Belum Siap",
    createdAt: "2026-05-18T11:00:00Z",
    updatedAt: "2026-05-18T11:00:00Z"
  },
  {
    id: "hb3",
    userId: "preview_user_id",
    barang: "Buku KIA (Pink), Fotokopi KTP, KK, & Kartu Asuransi/BPJS",
    kategori: "Dokumen Penting",
    jumlah: 1,
    status: "Belum Siap",
    createdAt: "2026-05-12T09:00:00Z",
    updatedAt: "2026-05-12T09:00:00Z"
  },
  {
    id: "hb_power",
    userId: "preview_user_id",
    barang: "Kabel charger & powerbank 10.000 mAh",
    kategori: "Perlengkapan Ayah",
    jumlah: 2,
    status: "Siap",
    createdAt: "2026-05-20T10:00:00Z",
    updatedAt: "2026-05-20T10:00:00Z"
  }
];

export const mockHospitalComparisons: HospitalComparison[] = [
  {
    id: "h1",
    userId: "preview_user_id",
    nama: "RSIA Bunda Jakarta",
    metodePersalinan: "Caesar ERACS (VIP)",
    estimasiBiaya: 32000000,
    fasilitasLayanan: ["Kamar Rawat VIP Privat", "Inisiasi Menyusu Dini (IMD)", "Klinik Laktasi Berlisensi", "Kamar NICU / PICU Lengkap", "Pendampingan Suami saat bersalin", "Layanan Foto Lahiran Newborn"],
    kelebihan: "Pro-ASI & IMD wajib pasca bersalin, metode pemulihan ERACS teruji cepat dalam 6 jam.",
    kekurangan: "Biaya tindakan kamar dan obat rawat tambahan relatif mahal.",
    lokasi: "Jl. Teuku Cik Ditiro No. 28, Menteng, Jakarta Pusat",
    catatanBiaya: "Paket dasar Rp 32 Juta sudah termasuk jasa tim dokter obgyn, anastesi, anak, kamar rawat 3 hari, obat bawa pulang standar, serta screening pendengaran OAE bayi.",
    kontak: "(021) 1500-799",
    linkGmap: "https://maps.app.goo.gl/BundaMenteng",
    rating: 5,
    createdAt: "2026-03-25T10:00:00Z",
    updatedAt: "2026-05-12T10:00:00Z"
  },
  {
    id: "h2",
    userId: "preview_user_id",
    nama: "RS Hermina Kemayoran",
    metodePersalinan: "Persalinan Normal Spontan (Kelas 1)",
    estimasiBiaya: 14500000,
    fasilitasLayanan: ["Kamar Kelas 1 (Isi 2 Pasien)", "Inisiasi Menyusu Dini (IMD)", "Rawat Gabung (Rooming-In)", "Klinik Laktasi Berlisensi", "Sertifikat Lahir & Pengurusan Dukcapil"],
    kelebihan: "Kebijakan sangat bersahabat dengan BPJS Kesehatan, dokter Obgyn andalan melimpah.",
    kekurangan: "Kamar kelas 1 kadang penuh sehingga berisiko dialihkan ke kelas lain.",
    lokasi: "Jl. Selangit Blok B-10 No. 8, Kemayoran, Jakarta Pusat",
    catatanBiaya: "Estimasi normal Rp 14.5 Juta tanpa penyulit, kamar Kelas 1 AC isi dua ranjang pasien. Mendukung rujukan BPJS bersalin bersyarat gawat darurat.",
    kontak: "(021) 2260-2525",
    linkGmap: "https://maps.app.goo.gl/HerminaKemayoran",
    rating: 4,
    createdAt: "2026-03-26T10:00:00Z",
    updatedAt: "2026-05-12T10:00:00Z"
  },
  {
    id: "h3",
    userId: "preview_user_id",
    nama: "Klinik Pratama Sehati",
    metodePersalinan: "Persalinan Normal Minimal Intervensi",
    estimasiBiaya: 6500000,
    fasilitasLayanan: ["Kamar AC Standar Nyaman", "Inisiasi Menyusu Dini (IMD)", "Rawat Gabung (Rooming-In)", "Pendampingan Suami saat bersalin", "Pijat Oksitosin Ibu Pasca Lahir"],
    kelebihan: "Biaya sangat bersahabat, pelayanan bersalin hangat berorientasi kenyamanan batin.",
    kekurangan: "Tidak memiliki unit NICU/PICU tersendiri untuk komplikasi berat darurat.",
    lokasi: "Jl. Margonda Raya Gg. Sejahtera No. 12, Pancoran Mas, Depok",
    catatanBiaya: "Biaya Rp 6.5 Juta bersih tipe mandiri. Sangat murah dan sudah termasuk kunjungan nifas bidan ke rumah (homecare) 2 kali gratis.",
    kontak: "0812-9900-1122",
    linkGmap: "https://maps.app.goo.gl/KlinikSehatiDepok",
    rating: 4,
    createdAt: "2026-03-27T10:00:00Z",
    updatedAt: "2026-05-12T10:00:00Z"
  }
];
